version: '3.8'
services:
  yongjin-mysql:
    container_name: yongjin-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: yongjin
      MYSQL_DATABASE: YONGJIN
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - ./mysql/CreateUserTable.sql:/docker-entrypoint-initdb.d/1.sql:ro
    security_opt:
      - seccomp:unconfined

  yongjin-redis:
    container_name: yongjin-redis
    image: redis:6.2
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - default