POST https://0.0.0.0:8080/CreateAccount
Content-Type: application/json

{
  "userID":"yongjin01",
  "userPW":"dydwls01"
}

###
POST https://0.0.0.0:8080/Login
Content-Type: application/json

{
  "userID":"yongjin01",
  "userPW":"dydwls01"
}

###
POST https://0.0.0.0:8080/MailBoxCheck
Content-Type: application/json

{
  "jwtAccessToken": "~~~~"
}

###
POST https://0.0.0.0:8080/MailBoxGetItem
Content-Type: application/json
        
{
  "jwtAccessToken": "~~~~",
  "Item" : "Welcome Item"
}

### 
POST https://0.0.0.0:8080/StageClear
Content-Type: application/json
        
{
  "jwtAccessToken": "~~~~",
  "score" : 50
}

###
POST https://0.0.0.0:8080/UsersRanking
Content-Type: application/json

{
  "jwtAccessToken": "~~~~"
}

###
POST https://0.0.0.0:8080/MyRanking
Content-Type: application/json

{
  "jwtAccessToken": "~~~~"
}

###
// 40 30 70 20 //
