POST https://localhost:5001/CreateAccount
Content-Type: application/json

{
  "userID":"yongjin01",
  "userPW":"dydwls01"
}

###
POST https://localhost:5001/Login
Content-Type: application/json

{
  "userID":"yongjin01",
  "userPW":"dydwls01"
}

###
POST https://localhost:5001/MailBoxCheck
Content-Type: application/json

{
  "jwtAccessToken": "~~~~"
}

###
POST https://localhost:5001/MailBoxGetItem
Content-Type: application/json
        
{
  "jwtAccessToken": "~~~~",
  "Item" : "Welcome Item"
}

### 
POST https://localhost:5001/StageClear
Content-Type: application/json
        
{
  "jwtAccessToken": "~~~~",
  "score" : 50
}

###
POST https://localhost:5001/UsersRanking
Content-Type: application/json

{
  "jwtAccessToken": "~~~~"
}

###
POST https://localhost:5001/MyRanking
Content-Type: application/json

{
  "jwtAccessToken": "~~~~"
}

###
// 40 30 70 20 //
